### ISSUE TITLE
iOS event support

### ISSUE THREAD

**Issue by voogryk** [taivo/parse-push-plugin#10]
Hi. U work is great! 

But I have some questions. How can I install ur plugin for iOS?

**Comment by taivo** [comment]
iOS is not yet supported, unfortunately. It's the 1st item on my todo list.

**Comment by ritterb82** [comment]
Just wanted to echo that i really love this branch because it actually works with background (coldstart, and you've wrote clear instructions) android notifications, but I'm really hoping that iOS support can be added soon.
