### ISSUE TITLE
How can we set small icon?

### ISSUE THREAD

**Issue by go2hyder** [taivo/parse-push-plugin#12]
How can we set small notification icon to show in status bar.Because there issue in icon on android lollipop(5.X.X)..

**Comment by taivo** [comment]
This is more a setup issue for `Parse.Push` than this plugin. 

According to https://parse.com/tutorials/android-push-notifications, you just put this

```xml
<meta-data android:name="com.parse.push.notification_icon" android:resource="@drawable/push_icon"/>
```

in the `application` tag of your `platforms/android/AndroidManifest.xml`. Then drop your monochromatic `push_icon` file in `platforms/android/res/drawable`

It's definitely useful to read the "Choose Your Push Icon" section of parse.com tutorial page I just linked.

**Comment by go2hyder** [comment]
@taivo 

Thankx for ur reply..That is very helpful...
I

**Comment by Aniket-ajency** [comment]
I have tried same thing mentioned above but still i am getting same issue. my icon is not visible when i receive push notification.  could any body help.

**Comment by taivo** [comment]
did you make sure your push icon is monochrome per android style guide? If so, does something else appear in place of your icon in the notif tray?
