### ISSUE TITLE
App crashes when running in background (coldstart)

### ISSUE THREAD

**Issue by jiju0nair** [taivo/parse-push-plugin#14]
When notification arrives and if the app is in background then app will crash. 
(App works fine with notifications in foreground and with notifications when app is killed )
 
This is the error message i get when app is in background and it crashes : 
"Unable to start receiver com.phonegap.parsepushplugin.ParsePushPluginReceiver: java.lang.NullPointerException"

Using cordova 5.1.1
Android 4.1.0

I installed the plugin and added the MainApplication that initializes parse as mentioned here.
I checked and confirmed that MainApplication is called. It is called when app is killed and notification arrives but not when app is in background and notification arrives may be thats causing the issue here. 

Help needed here.
Regards.

Complete Error :

10-29 16:30:41.172: D/ParsePushPluginReceiver(25847): onPushReceive - context: android.app.ReceiverRestrictedContext@4183e018
10-29 16:30:41.232: D/AndroidRuntime(25847): Shutting down VM
10-29 16:30:41.232: W/dalvikvm(25847): threadid=1: thread exiting with uncaught exception (group=0x40dde930)
10-29 16:30:41.272: E/AndroidRuntime(25847): FATAL EXCEPTION: main
10-29 16:30:41.272: E/AndroidRuntime(25847): java.lang.RuntimeException: Unable to start receiver com.phonegap.parsepushplugin.ParsePushPluginReceiver: java.lang.NullPointerException
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2459)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at android.app.ActivityThread.access$1600(ActivityThread.java:153)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at android.os.Looper.loop(Looper.java:176)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at android.app.ActivityThread.main(ActivityThread.java:5302)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at java.lang.reflect.Method.invoke(Method.java:511)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at dalvik.system.NativeStart.main(Native Method)
10-29 16:30:41.272: E/AndroidRuntime(25847): Caused by: java.lang.NullPointerException
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at android.webkit.WebViewClassic.setNetworkAvailable(WebViewClassic.java:4224)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at android.webkit.WebView.setNetworkAvailable(WebView.java:731)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at org.apache.cordova.engine.SystemWebViewEngine$1.setNetworkAvailable(SystemWebViewEngine.java:112)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at org.apache.cordova.NativeToJsMessageQueue$OnlineEventsBridgeMode$2.run(NativeToJsMessageQueue.java:340)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at android.app.Activity.runOnUiThread(Activity.java:4843)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at org.apache.cordova.engine.SystemWebViewEngine$1.runOnUiThread(SystemWebViewEngine.java:116)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at org.apache.cordova.NativeToJsMessageQueue$OnlineEventsBridgeMode.onNativeToJsMessageAvailable(NativeToJsMessageQueue.java:336)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at org.apache.cordova.NativeToJsMessageQueue.enqueueMessage(NativeToJsMessageQueue.java:251)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at org.apache.cordova.NativeToJsMessageQueue.addPluginResult(NativeToJsMessageQueue.java:240)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at org.apache.cordova.CordovaWebViewImpl.sendPluginResult(CordovaWebViewImpl.java:307)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at org.apache.cordova.CallbackContext.sendPluginResult(CallbackContext.java:63)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at com.phonegap.parsepushplugin.ParsePushPlugin.jsCallback(ParsePushPlugin.java:124)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at com.phonegap.parsepushplugin.ParsePushPlugin.jsCallback(ParsePushPlugin.java:113)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at com.phonegap.parsepushplugin.ParsePushPluginReceiver.onPushReceive(ParsePushPluginReceiver.java:47)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at com.parse.ParsePushBroadcastReceiver.onReceive(ParsePushBroadcastReceiver.java:117)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2452)
10-29 16:30:41.272: E/AndroidRuntime(25847): 	... 10 more

**Comment by fcorneli** [comment]
This seems more like a bug within Cordova itself as I also got that same NPE within my app.
