### ISSUE TITLE
'urlHash' not working in ionic..

### ISSUE THREAD

**Issue by go2hyder** [taivo/parse-push-plugin#15]
I am using this plugin in ionic.

I set  `String urlHash = intent.hasExtra("urlHash") ? intent.getStringExtra("urlHash") : "";
    loadUrl(launchUrl + urlHash);` to Mainactivity,java.
And send a notification with parse dashboard as json
(
               ` {"alert":"test",
"urlHash":"#app/search"
}`
          )
The Notification is coming. But when I click notification in status bar app open in normal home page.Not to the 'search' page..How to integrate it with ionic?    (but if application is in background `ParsePushPlugin.on('openPN', function(pn){
    if(pn.urlHash){
        window.location.hash = hash;
    }
});` is working).The problem occurs if the application is not in background.. 

Thank U

**Comment by FrnandMG** [comment]
Could you please show your full Mainactivity,java file. I tried it on a simple phonegap app, send the push {"alert":"test", "urlHash":"#page3" } when I click on the notification nothing happens. 
the application does not open.

**Comment by kamikaz1k** [comment]
@go2hyder Should it not be #/app/search?
