### ISSUE TITLE
not working with android 4.2.2

### ISSUE THREAD

**Issue by hussainanver52** [taivo/parse-push-plugin#16]
I tried installing to android 4.2.2 its subscribing and retrieving installation id properly but not receiving push notification where android 5 + receives

**Comment by taivo** [comment]
Would you be able to post the logcat here? I don't have a 4.2.2 device at the moment to replicate your result.

Also, on your 4.2.2 setup, when a pn arrives, does it crash your app or is silent like nothing happened.

**Comment by hussainanver52** [comment]
i dont know how to get a logcat i am sorry because i am not able to debug it using chrome dev tools and when a pn arrives its silent like nothing happened and from parse log i can see its not even delivered

thanks for the reply

**Comment by hussainanver52** [comment]
i got following log when sending push 
call to ParsePushPlugin.subscribe blocked the main thread for 27ms. Plugin should use CordovaInterface.getThreadPool()

**Comment by hussainanver52** [comment]
V/IntentResolver(  719): Action list: [Landroid.content.pm.PackageParser$ServiceIntentInfo;@41af7268
V/IntentResolver(  719): Action list: [Landroid.content.pm.PackageParser$ServiceIntentInfo;@41af7268

and also the above notification

**Comment by taivo** [comment]
This page has been quiet for a long time + the code has changed significantly since. Closing.
