### ISSUE TITLE
Provide a way to update Installation object

### ISSUE THREAD

**Issue by sesubash** [taivo/parse-push-plugin#17]
Need a method to update Installation object, like adding username as a column.

**Comment by mrsubtle** [comment]
Can you not do this via the JavaScript SDK when the getInstallationId returns the ID?

**Comment by sesubash** [comment]
It is not possible via Javascript SDK. We need to use REST API or through mobile client SDK's to modify Installation object as per this link https://www.parse.com/docs/js/guide#push-notifications-installations.

**Comment by mrsubtle** [comment]
I guess they don’t consider the Javascript SDK a “Client SDK”? As per this line: "Note that Installation data can only be modified by the client SDKs, the data browser, or the REST API."
-- 
Richard Bennett
Sent with Airmail

On December 8, 2015 at 11:52:59 PM, Subash Selvaraj (notifications@github.com) wrote:

It is not possible via Javascript SDK. We need to use REST API or through mobile client SDK's to modify Installation object as per this link https://www.parse.com/docs/js/guide#push-notifications-installations.
