### ISSUE TITLE
onReceive not triggered in iOS on inbound PN

### ISSUE THREAD

**Issue by mrsubtle** [taivo/parse-push-plugin#19]
The onReceive event is not triggered when a new PN is received by the device.

I am setting an event listener like so:

    ParsePushPlugin.on('onReceive', function(pn){
        console.log(pn);
    });

**Comment by taivo** [comment]
Hello,
As mentioned in the docs, my fork doesn't have iOS support just yet. Whatever code is there is carried over from the upstream fork. That said, I'm starting to work on iOS support now. May take a while because I'm new to development on iOS and OSX.
