### ISSUE TITLE
iOS - wrap swizzling in a dispatch_once

### ISSUE THREAD

**Issue by dirkpostma** [taivo/parse-push-plugin#26]
According to

http://nshipster.com/method-swizzling

...swizzling should always be done in a dispatch_once:

_because swizzling changes global state, we need to take every precaution available to us in the runtime. Atomicity is one such precaution, as is a guarantee that code will be executed exactly once, even across different threads. Grand Central Dispatch’s dispatch_once provides both of these desirable behaviors, and should be considered as much a standard practice for swizzling as they are for initializing singletons._

**Comment by taivo** [comment]
As far as I know, AppDelegate is a singleton and that should mean it's only loaded once so we're safe, no? We're only swizzling in AppDelegate.
