### ISSUE TITLE
silent notifs

### ISSUE THREAD

**Issue by xxvii27** [taivo/parse-push-plugin#33]
on android, silent notification seems not working. I keep getting blank notifications added to the tray.

**Comment by alifradityar** [comment]
Yeah, I also got this issue

**Comment by taivo** [comment]
I've never seen this problem but I've just upgraded the code significantly. Are you still seeing this issue in the new code?

**Comment by xxvii27** [comment]
I am using the parse.com branch, as I haven't migrate yet.

**Comment by xxvii27** [comment]
Want to reopen this issue, as it still persist event after upgrading
