### ISSUE TITLE
Cold start in iOS

### ISSUE THREAD

**Issue by fmendoza** [taivo/parse-push-plugin#34]
Until now, everything is working great with this plugin. I got notifications on iOS and Android, callbacks are working, even cold start on Android, but I can't find a way to do this last thing on iOS.

Anyone can share a solution to this?

**Comment by taivo** [comment]
I fixed a crash on cold start issue in iOS about 2 weeks ago. It seems to work fine now on my iphone. Just in case you haven't updated your local copy, please do. You can do that by removing the plugin from your cordova project then re-add it.

If you still have problems, please give some details on how it crashed. Error logs are also great. Thanks.

**Comment by fmendoza** [comment]
I mean... this works out the box? Do I have to setup something like Android (MainActivity.java, js callbacks, etc)?

I saw the following in the docs: "iOS: ... haven't tried yet but probably should be handled in AppDelegate.didReceiveRemoteNotification"

**Comment by taivo** [comment]
That comment is in the `urlHash` section and is meant for directly opening a specific url upon cold start.

As for cold starting an app when a user opens a notification, in iOS I queue up the notification. After the js side is properly initialized, the js plugin will register its callback with native, and native will then flush the stored notification queue by triggering `openPN`. Your code should catch the openPN event to process the message that was used to cold start your app.

At least that's what I thought I coded :) Try that and let me know if it works.

**Comment by Kira2** [comment]
Hi,

I saw this PR https://github.com/taivo/parse-push-plugin/pull/27 to try to fix cold start. There is a discussion about it, and it helped me a lot. Maybe it can help you.

**Comment by taivo** [comment]
Works now. There is also an example ionic app and parse-server setup to verify that it works.

Also, installation is now super simple. Just `cordova plugin add` and set a couple of config.xml parameters. No more messing with Java, AndroidManifest, or objective C. Also, no more plugin add --variable.

Closing this. Thank you all for your insights.
