### ISSUE TITLE
PPNS - Outdated device

### ISSUE THREAD

**Issue by pgerlich** [taivo/parse-push-plugin#38]
Whenever I attempt to setup plugin I'm running into the outdated device error. 

Any thoughts?

**Comment by ladmerc** [comment]
I have same issue. Unable to send Push notifications from the dashboard. I get same error message

**Comment by taivo** [comment]
You may find these stackoverflow pages helpful:

1. [http://stackoverflow.com/questions/32476692/outdated-device-parse-push-notification-to-android-devices](http://stackoverflow.com/questions/32476692/outdated-device-parse-push-notification-to-android-devices)
2. [http://stackoverflow.com/questions/34499145/android-parse-push-notifications-not-working-outdated-device](http://stackoverflow.com/questions/34499145/android-parse-push-notifications-not-working-outdated-device)

@pgerlich , how did you solve this problem for yourself?

**Comment by paulgerlich-wf** [comment]
@ladmerc The problem you are having may be due to you not signing your APK. That was the issue I was running into.

**Comment by paulgerlich-wf** [comment]
@taivo Are there any features you've got on the backlog that you need help with? I'd be happy to help contribute.

**Comment by taivo** [comment]
@paulgerlich-wf, wish you can see how big I'm grinning at that offer. Hopefully I don't make you regret making it. Would really love to get passed a problem with Windows support right now, issue #42 

If you have a new usecase that is relevant to this plugin, feel free to propose it as an issue and we can go from there.

**Comment by ladmerc** [comment]
Thanks @taivo, however none of the above solutions worked.

One thing I noticed though: the first link suggested commenting out some lines in Manifest. When I build again, the lines are uncommented. I think the plugin automatically does that

**Comment by ladmerc** [comment]
@paulgerlich-wf I'm running on genymotion. I doubt I'm to sign an apk for it

**Comment by taivo** [comment]
"Installation not saved sounds" like a parse setup thing. Did you set the `config.xml` preference `ParseClientKey` with the Android/iOS client key? (Not the javascript key).

Please see if the General Troubleshooting section at the bottom of the README would be applicable to your case.

**Comment by ladmerc** [comment]
Yeah I set everything correctly. Odd thing is that installations get saved when I run app in emulator, but not from device.

I'm considering OneSignal, as I've run out of viable options to get this to work

**Comment by paulgerlich-wf** [comment]
@ladmerc Are you sure that it's generating a signed APK? Sometimes Android studio will generate unsigned APK's , even in debug mode. That was the issue I was using (and I also use Genymotion.)

**Comment by paulgerlich-wf** [comment]
@taivo I'd be happy to take a look tomorrow, although I've not done any Windows development.

**Comment by taivo** [comment]
@ladmerc it's hard to help debugging without logs. Are you able to give us the logcat? I'm glad to help you get to the bottom of this. Chances are that it's just a setup, config thing.

Also, if possible, please paste or attach AndroidManifest.xml and config.xml here.

You can also try to build the included example app in this plugin's "example" directory. Instructions are in that directory. With the example app working, you can then see what the difference is between it and your app.

**Comment by ladmerc** [comment]
I apologize if the info I'm providing is too verbose

My config.xml

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<widget id="com.xxx.yyy" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <name>myApp</name>
  <description>
        lorem ipsum. 
    </description>
  <author email="example@example.com" href="http://example.com/">
      John Doe
    </author>
  <content src="index.html"/>
  <access origin="fb"/>
  <access origin="*"/>
  <allow-intent href="fb"/>
  <allow-intent href="*"/>
  <allow-navigation href="*"/>
  <preference name="ParseAppId" value="my-app-id-from-parse"/>
  <preference name="ParseClientKey" value="my-client-key"/>
  <preference name="ParseServerUrl" value="PARSE_DOT_COM"/>
  <preference name="webviewbounce" value="false"/>
  <preference name="UIWebViewBounce" value="false"/>
  <preference name="DisallowOverscroll" value="true"/>
  <preference name="BackgroundColor" value="0xff0000ff"/>
  <preference name="android-minSdkVersion" value="16"/>
  <preference name="BackupWebStorage" value="none"/>
  <preference name="SplashScreen" value="screen"/>
  <preference name="SplashScreenDelay" value="3000"/>
  <preference name="CrosswalkAnimatable" value="true"/>
  <preference name="xwalkVersion" value="19+"/>
  <preference name="xwalkCommandLine" value="--disable-pull-to-refresh-effect"/>
  <preference name="xwalkMode" value="embedded"/>
  <preference name="xwalkMultipleApk" value="true"/>
  <feature name="StatusBar">
    <param name="ios-package" onload="true" value="CDVStatusBar"/>
  </feature>
  <platform name="ios">
    <feature name="Toast">
      <param name="ios-package" value="Toast"/>
    </feature>
    <icon height="57" src="resources/ios/icon/icon.png" width="57"/>
    <icon height="114" src="resources/ios/icon/icon@2x.png" width="114"/>
    <icon height="40" src="resources/ios/icon/icon-40.png" width="40"/>
    <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80"/>
    <icon height="50" src="resources/ios/icon/icon-50.png" width="50"/>
    <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100"/>
    <icon height="60" src="resources/ios/icon/icon-60.png" width="60"/>
    <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120"/>
    <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180"/>
    <icon height="72" src="resources/ios/icon/icon-72.png" width="72"/>
    <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144"/>
    <icon height="76" src="resources/ios/icon/icon-76.png" width="76"/>
    <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152"/>
    <icon height="29" src="resources/ios/icon/icon-small.png" width="29"/>
    <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58"/>
    <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87"/>
    <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640"/>
    <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750"/>
    <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242"/>
    <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208"/>
    <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048"/>
    <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024"/>
    <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536"/>
    <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768"/>
    <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640"/>
    <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320"/>
  </platform>
  <platform name="android">
    <feature name="Toast">
      <param name="android-package" value="nl.xservices.plugins.Toast"/>
    </feature>
    <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png"/>
    <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png"/>
    <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png"/>
    <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png"/>
    <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png"/>
    <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png"/>
    <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png"/>
    <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png"/>
    <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png"/>
    <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png"/>
    <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png"/>
    <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png"/>
    <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png"/>
    <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png"/>
    <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png"/>
    <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png"/>
    <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png"/>
    <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png"/>
  </platform>
</widget>`

My Manifest

`<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="1" android:versionName="0.0.1" package="com.xxx.yyy" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@drawable/icon" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <service android:name="com.parse.PushService" />
        <receiver android:exported="false" android:name="github.taivo.parsepushplugin.ParsePushPluginReceiver">
            <intent-filter>
                <action android:name="com.parse.push.intent.RECEIVE" />
                <action android:name="com.parse.push.intent.DELETE" />
                <action android:name="com.parse.push.intent.OPEN" />
            </intent-filter>
        </receiver>
        <receiver android:name="com.parse.GcmBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>
    </application>
    <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="23" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <permission android:name="${applicationId}.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />
</manifest>
`

Also, I followed the instructions in the link you provided https://stackoverflow.com/questions/34499145/android-parse-push-notifications-not-working-outdated-device, but whenever I build, my changes get overwritten again.

**Comment by taivo** [comment]
Those links were just research links, something to try. It's late night where I am so I'm going to review your log tomorrow and see if I can give you any help.

**Comment by taivo** [comment]
Also, when you say "I noticed the deviceToken and GCMSenderId fields are empty", where did you notice it being empty? in the apk? in some log statement?

**Comment by taivo** [comment]
Ok, we may be very close to solving this. One thing I can see right away is your manifest <application> tag is missing the attribute `android:name="github.taivo.parsepushplugin.ParsePushApplication"`

That attribute is added by this plugin's `before_install` hook script. The script is supposed to check if your <application> tag has the attribute `android:name` set. If already set, it will leave things alone. If not set, it will set to the above value and save.

So 2 things could have happened. 

1. One is the hook script failed. Can you verify this for me by `cordova plugin remove parse-push-plugin` then `cordova plugin add https://github.com/taivo/parse-push-plugin`. Please observe the console to see if there is any error message. Then check to see if the `android:name` attribute is correctly set in the manifest.

2. If the attribute is set correctly but then disappear again after you've built the app, then something else in your build process must have removed the `android:name` attribute. But let's verify it first by building the app, then check the manifest.

**Comment by ladmerc** [comment]
Hi, I meant I noticed the deviceToken and GCMSenderId fields are empty in my Installations table in Parse.

I uninstalled and reinstalled the plugin. The Manifest.xml seems correct as you indicated, however now I can't even save installations.

**Comment by cleever** [comment]
@ladmerc Where are you saving the cordova plugin and platform versions?
I can not see them in your config.xml.

If you are not saving anywhere, please run the followings commands to save in your config.xml

```
$ cordova platform save
$ cordova plugin save
```

Then run the platforms update:

`$ cordova platform update <platform> --save`

And then, update your plugins:

```
$ npm install -g cordova-check-plugins
$ cordova-check-plugins --update=auto
```

**Comment by ladmerc** [comment]
@cleever, thanks for the help, and sorry to drag this on. I followed all the steps again and ran on genymotion. Installation not saved.

Removed plugin, platform. Added platform, plugin. Ran again, app crashes. Everytime I remove and readd platform followed by plugin, it crashes

Thanks for the assistance, but after a week on this, maybe I should ditch Parse and consider other options. Cheers

**Comment by taivo** [comment]
This is super weird. So even after the build process, `android:name="github.taivo.parsepushplugin.ParsePushApplication"` is still in the application tag of AndroidManifest?

If your app is something that you can share as a whole, I'd be glad to take a look. It's cool if you decide to move on. I understand completely.

**Comment by taivo** [comment]
@paulgerlich-wf if you want something easy to warm up with, pr #28 has some merge conflicts that needs to be resolved before merging is possible. I'm not sure you can resolve it on the same pr but you can probably pull that code into your fork, resolve then create a new pr.

Badge method would be a pretty useful thing to have. So if you want to, go for it.

**Comment by paulgerlich-wf** [comment]
Absolutely. Ill check it out on Monday as I'm out of town for the weekend.
