### ISSUE TITLE
windows & iOS support

### ISSUE THREAD

**Issue by filfat** [taivo/parse-push-plugin#4]
Hi, thanks for the so far awesome work!
It would be great if windows(uwp) and iOS support could be added to this project.

Thanks :)

**Comment by luco** [comment]
+1 on this. I miss iOS so much. That would be great.

**Comment by taivo** [comment]
iOS support has arrived! Happy birthday and let me know how well it works for you :)

**Comment by taivo** [comment]
Not sure when I can get windows phone support. I don't have a windows phone.

**Comment by filfat** [comment]
@taivo This issue should still be open as there isn't any support for Windows,
Also, I was refereeing to Windows 10 (UWP) not Windows Phone (Silverlight).

Cheers :)

**Comment by taivo** [comment]
Sorry @filfat, I can't foresee any free time to look into UWP unless my main projects require it. I will have to regard this as a `won't fix` and keep the issue closed. If you have a chance to work on a PR for UWP support, I'd be happy to merge

**Comment by filfat** [comment]
@taivo I had in plan to work on a PR, but since the recent announcement there's really no point to beat a soon-to-be dead horse http://blog.parse.com/announcements/moving-on/

**Comment by taivo** [comment]
w
t
f

**Comment by tavojavi** [comment]
Wooowwww can´t believe it...

It will be good if we can start a thread where we can analize other services, so people is aware of options, what do you think?

**Comment by campers** [comment]
I'm busy working on what I'm confident will be the best migration option. Something I'd already been planning, and their server code will only make it easier.

**Comment by taivo** [comment]
@tavojavi, yea that would be cool. Let me know where you place this thread. My initial thought was to look into https://github.com/phonegap/phonegap-plugin-push and Amazon SNS service.

@campers, do share when you have a chance, even if it's only a draft version. I'm debating whether to migrate data and use the open source Parse Server or just use Django and spin up my own API since my database schema and client/server communication is fairly clear at this point.

**Comment by campers** [comment]
It will take a little bit to implement everything how I'm planning, there's plenty of time to migrate. I've just made a quick website you can keep updated at http://appstack.systems/
