### ISSUE TITLE
null Installation ID

### ISSUE THREAD

**Issue by andrescruz** [taivo/parse-push-plugin#43]
I installed the plugin to my Ionic project but I'm getting a null value as a result from ParsePushPlugin.getInstallationId. I'm using a parse-service provider (parseground.com) so I'm not sure if this may have something to do with the way its installed.

**Comment by taivo** [comment]
We need a bit more info to solve this problem. Is this Android or iOS? Are you able to setup a local toy server for your app to see if push notification works? I wrote a brief [quickstart guide](http://taivo.github.io/guides/parse-server-for-local-development) that might help.

Also, there is a chance that serverUrl might have been mispelled or incorrect in your plugin setup.

**Comment by andrescruz** [comment]
Thanks for the quick response!

I haven't set up the local server. It is for iOS, for now, and the serverUrl is correct. Also, I made sure that the config.xml file contained the preference tags with the correct values. 

Let me know what other details I can provide to you to debug this issue. Thanks!

**Comment by taivo** [comment]
I've just rigged up a simple test app based on the ionic blank template, and I ran into a weird issue as described [here](https://github.com/driftyco/ng-cordova/issues/8). Search for Elvistelefon comment on Aug 6, 2014.

Basically the `$ionicPlatform.ready` block in `app.js` died during the setup for keyboard plugin. This seems to prevent other plugins' initialization to happen properly for my simple setup. Removing and re-adding the keyboard plugin somehow fixed things. After I did just that, I was able to retrieve my installationId just fine.

Not sure if that's related to your problem but it should only take a couple minutes to find out.

**Comment by taivo** [comment]
Hey @andrescruz , were you able to fix your problem?

If not, please try it out on the example app setup I have added. There is a sample ionic app designed for quick testing parse-push and there is also a corresponding parse-server app to go with it. All instructions are there in the [example](https://github.com/taivo/parse-push-plugin/tree/master/example) dir.
