### ISSUE TITLE
Usage of this plugin with cordova-plugin-admob

### ISSUE THREAD

**Issue by jadsalhani** [taivo/parse-push-plugin#44]
The AdMob plugin references the google-playservices through its gradle dependancies.

As mentioned [here](https://github.com/floatinghotpot/cordova-admob-pro/wiki/Difference-of-Plugin-IDs#3-build-error-with-message-multiple-dex-files-define-lcomgoogle), could you please update the android-support-lib dependancy through the gradle dependancies as well so that they are compatible?

Else I receive this error

``````````````

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)

	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)

`````````````````

Thank you

**Comment by taivo** [comment]
I switched Android config to use plugin.xml's `<framework>` instead of jar. Give it a try.

**Comment by ankitjainOfficial** [comment]
@taivo I could not follow your instructions very clearly. I am having the same issue. This is my plugins/com.phonegap.parsepushplugin/plugin.xml (The android part):

```
<platform name="android">
        <config-file target="res/xml/config.xml" parent="/*">
            <feature name="ParsePushPlugin">
                <param name="android-package" value="com.phonegap.parsepushplugin.ParsePushPlugin" />
            </feature>
        </config-file>
        <config-file target="AndroidManifest.xml" parent="/manifest/application">
          <service android:name="com.parse.PushService" />
          <receiver android:exported="false" android:name="com.phonegap.parsepushplugin.ParsePushPluginReceiver" android:exported="false">
            <intent-filter>
                <action android:name="com.parse.push.intent.RECEIVE" />
                <action android:name="com.parse.push.intent.DELETE" />
                <action android:name="com.parse.push.intent.OPEN" />
            </intent-filter>
          </receiver>
          <receiver android:name="com.parse.GcmBroadcastReceiver"
              android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
              <action android:name="com.google.android.c2dm.intent.RECEIVE" />
              <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
              <category android:name="$PACKAGE_NAME" />
            </intent-filter>
          </receiver>
        </config-file>
        <config-file target="AndroidManifest.xml" parent="/manifest">
          <uses-permission android:name="android.permission.INTERNET" />
          <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
          <uses-permission android:name="android.permission.WAKE_LOCK" />
          <uses-permission android:name="android.permission.VIBRATE" />
          <uses-permission android:name="android.permission.GET_ACCOUNTS" />
          <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
          <permission android:protectionLevel="signature" android:name="$PACKAGE_NAME.permission.C2D_MESSAGE" />
          <uses-permission android:name="$PACKAGE_NAME.permission.C2D_MESSAGE" />
        </config-file>

        <framework src="com.parse:parse-android:1.13.0" />
        <framework src="com.parse.bolts:bolts-android:1.4.0" />
        <framework src="com.android.support:support-v4:+" />

        <source-file src="src/android/parse/Parse-1.10.1.jar" target-dir="libs" framework="true" />
        <source-file src="src/android/ParsePushPlugin.java" target-dir="src/com/phonegap/parsepushplugin" />
        <source-file src="src/android/ParsePushPluginReceiver.java" target-dir="src/com/phonegap/parsepushplugin" />
     </platform>
```

Please let me know, where I have gone wrong. As I am still facing multi dex problem.

Thank you.

**Comment by taivo** [comment]
Sorry I haven't had the time to update the parse-com branch. Since parse.com is shutting down in a few months, it doesn't make sense to spend significant time on it.

That said, it looks like you have modified your plugin.xml to use `framework` tags. Are you sure the Multi dex issue relates to this plugin? Also, have you deleted all the old jar file that was installed to your project by this plugin? 

You can check your error log to see which .jar is being duplicated in your project, thus causing the multiple dex problem. Then figure out which duplicate can be deleted and still allow your whole project to build (probably just by trial and error). Finally you can write an `after_prepare` hook to automate this deletion so you won't have to deal with the annoyance the next time you remove/add plugins. 

This is what I had to do with the parse-com branch when I used it with the Facebook Connect plugin.

**Comment by jadsalhani** [comment]
@taivo Thank for the quick reply and fix! I was hoping though to have the fix on the parse-com branch since the app server being used still hasn't  been migrated. Will you implement the fix for the parse-com branch or shall I do it?

What are the steps to apply the fix? Simply copy the `framework` tag from the main branch and replace the `jar` tags with it right?

**Comment by taivo** [comment]
Just turned on computer and saw your message. This was a 30 second task for me so I went ahead and do it. Try it out.

**Comment by jadsalhani** [comment]
@taivo Awesome thanks a lot! I'll try it out and let you know what happens

**Comment by taivo** [comment]
I've just added legacy parse.com support to the master branch. It has a lot of updates and bug fixes that the parse-com branch doesn't have, including cold start stuff. Also, the setup is a lot easier, no more messing with Objective C, AndroidManifest or java.

You guys can save yourself a lot of time by just removing the parse-com branch plugin and add this one.
