### ISSUE TITLE
iOS didFinishLaunchingWithOptions returning yes locks up app

### ISSUE THREAD

**Issue by pgerlich** [taivo/parse-push-plugin#45]
When following the parse.com version of the readme in the setup section (https://github.com/taivo/parse-push-plugin/tree/parse-com#ios-setup) returning "YES" instead of "return [super application:application didFinishLaunchingWithOptions:launchOptions];" causes the app to hang on a black screen.

**Comment by taivo** [comment]
fixed. Good catch, @pgerlich

**Comment by taivo** [comment]
I've just added legacy parse.com support to the master branch. It has a lot of updates and bug fixes that the parse-com branch doesn't have, including cold start stuff. Also, the setup is a lot easier, no more messing with Objective C, AndroidManifest or java.

@pgerlich , please switch to it so you can save yourself time dealing with bugs from the parse-com branch.

**Comment by paulgerlich-wf** [comment]
Can do. Thanks for letting me know.
Now just to get off parse.com
