### ISSUE TITLE
cold start and background push notifications not working on iOS and Android

### ISSUE THREAD

**Issue by jackread** [taivo/parse-push-plugin#47]
Hey, I'm really liking this plugin so far, but I have a feeling I may be doing something wrong...

On my 'deviceready' event I'm binding to 'receivePN'..
<code><pre>ParsePushPlugin.on('receivePN', function(e){
    console.log(e);
});</pre></code>

This is working fine while the app is open, however when in background or full cold-start, clicking the notification is only opening the app... not getting and 'receivePN' events.

In Xcode logs I can see "cold-start notification has no userInfo".
Can't see anything in android logcat.

Any ideas?

**Comment by taivo** [comment]
Hello @jackread, when you open the app from background or cold start, 'openPN' should be the event to catch for.

Without zooming into the code, I can't remember exactly if I also forwarded 'receivePN` when user opens a notification from the tray. I wanted to get you rolling quickly though, so try 'openPN' :)

**Comment by jackread** [comment]
Hey @taivo thanks for the quick reply.

You're totally right, openPN works!
