### ISSUE TITLE
Control when to ask for permission on iOS

### ISSUE THREAD

**Issue by jackread** [taivo/parse-push-plugin#48]
I'd like to be able to be able to setup push notifications as part of an onboarding experience and ask for permission when a user taps on a button... rather than as soon as the app starts.

I'm happy to work on pull request for this, just wondering if you have any thoughts on how doable it might be!

**Comment by taivo** [comment]
Great idea! I'm all for it.

I have not done this previously so I can't say how difficult it would be. I have some thoughts that you may find useful:

1. The code block that does push registration is this one in `AppDelegate+parsepush.m`
```objectiveC
UIUserNotificationType userNotificationTypes = (UIUserNotificationTypeAlert | UIUserNotificationTypeBadge | UIUserNotificationTypeSound);
      UIUserNotificationSettings *settings = [UIUserNotificationSettings settingsForTypes:userNotificationTypes categories:nil];
      [application registerUserNotificationSettings:settings];
      [application registerForRemoteNotifications];
```

2. You'll need a way to know whether we already have permission so the next time the app starts, you can just automatically register the device exactly the way it's done now.

3. You'll need to introduce a new function to our API to kick off the registration and that function needs to be idempotent.

4. I want to keep the current registration method as the default behavior. That way a new user can know if push notification works or not before moving on with more advanced configurations. So if you could implement this feature under a new config.xml preference, for example, ParseManualRegistration or ParseAutoRegistration, that would be awesome. Introducing a new preference is easy, just look at `didFinishLaunchingWithOptions` in [AppDelegate+parsepush.m](../blob/master/src/ios/AppDelegate+parsepush.m) to see how it's done for appId and serverUrl

I do have a preference of keeping the registration done where it is right now as default, and use a `config.xml` parameter to 


P.S.
My current item is to add UWP support so I am not able to look into this immediately. Your pull request would be much welcomed!

**Comment by jackread** [comment]
Thanks. I got a quick and dirty version of this done last night, didn't see your message but I think we had the same ideas in terms of how to implement. 

I'll put in a pull request later today... Got to get this app submitted now!!

**Comment by taivo** [comment]
I'd love to see the app if it's okay.

**Comment by jackread** [comment]
@taivo sure... I can't post here but send me an email jack[at]fan.si and I can show you 👍
