### ISSUE TITLE
Custom sounds and multitext for Android

### ISSUE THREAD

**Issue by pablo-gonzalez** [taivo/parse-push-plugin#49]
Thank you for your plugin. It is great.
I am not a Android programmer but I could manage it to make some modifications in method getNotification in ParsePushPluginReceiver.java

```
		if(pnData.has("alert")){
			builder.setContentText(pnData.optString("alert"));
			// PG - Multiline text
			builder.setStyle(new NotificationCompat.BigTextStyle().bigText(pnData.optString("alert")));//add this line
		}

		if (!ParsePushPlugin.isInForeground()) {			
			// PG - Custom sound
			if(!pnData.has("sound")){
				builder.setSound(android.provider.Settings.System.DEFAULT_NOTIFICATION_URI);
			} else {
				int resourceId = context.getResources().getIdentifier(pnData.optString("sound"), "raw", context.getPackageName());
				Uri soundUri = Uri.parse("android.resource://" + context.getPackageName() + "/" + resourceId);
				builder.setSound(soundUri);
			}			
		}

```
You have to put custom sounds in /res/raw folder. Por instance: test.mp3
In Parse dashboard you have to send a JSON message:

```
{
  "alert": "New Push with custom sound",
  "sound": "test"
}

```
It works fine sending a JSON message with "sound" in the payload.
If the JSON message does not have "sound" it plays the default notification sound for Android as expected.

However if I send a Text message in Parse it does not play any sound at all.
The default notification sound should be played. What am I doing wrong?

Thanks in advance,
Pablo

**Comment by taivo** [comment]
Hi Pablo,
From what I understand, a text message from the Parse dashboard will end up being sent as a json object with an `alert` field so `pnData` will be json any way. The problem you are describing (where there is a difference between text vs json) sounds really strange to me.

Since you are tinkering with `getNotification` already, have you tried to put a `Log.d()` to print out the content of `pnData`? That would help seeing how else text messages sent from Parse are different from json sent from Parse.

**Comment by pablo-gonzalez** [comment]
Thank you for the reply. I will try that to debug.

**Comment by pablo-gonzalez** [comment]
Hi Taivo. I could find the reason of this behaviour.
When you send a message as Plain Text, the key "sound" is added to the payload with the value default by Parse Dashboard.
{
"alert": "message",
"sound": "default"
}
That's way there was not sound at all in my code because there is not "default" file in res/raw.

**Comment by taivo** [comment]
Ah, makes sense. Now we both have learned something new. Thanks!
