### ISSUE TITLE
Sound & Vibration on receive

### ISSUE THREAD

**Issue by filfat** [taivo/parse-push-plugin#5]
Allowing us to use sound and vibration when the user receives a notification would improve the user experience a lot.

Thanks.

**Comment by tavojavi** [comment]
A lot! I´m trying to add it for Android, but not an expert.

**Comment by tavojavi** [comment]
Hello, I´ve just saw a pull request, it works, look for adding this to the receiver:

if (!ParsePushPlugin.isInForeground()) {
			builder.setSound(android.provider.Settings.System.DEFAULT_NOTIFICATION_URI);
		}

**Comment by taivo** [comment]
I merged that PR yesterday. Thank you @tavojavi for all your constructive feedback :)
