### ISSUE TITLE
crash on getInstallationId

### ISSUE THREAD

**Issue by Br3nda** [taivo/parse-push-plugin#55]
I have tried to debug on the console, runnign this:
```
ParsePushPlugin.initialize(function() { App.log.debug("INIT!"); });
```
returns/logs:

```
"INIT!"
undefined
```

However if i try to get installationId like this
```
    ParsePushPlugin.getInstallationId(function(id) {
         // note that the javascript client has its own installation id,
         // which is different from the device installation id.
          App.log.debug("Push notification device installationId: " + id);
      }, function(e) {
          App.log.error('error');
      });
```
I get return "undefined", but immediately followed by a crash. No other output.

The exception throw is:
``` 
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File com.parse.ParsePlugins.getParseDir()' on a null object reference
at com.parse.ParseCorePlugins.getCurrentInstallationController(ParseCorePlugins.java:273)
at com.parse.ParseInstallation.getCurrentInstallationController(ParseInstallation.java:52)
at com.parse.ParseInstallation.getCurrentInstallation(ParseInstallation.java:57)
at github.taivo.parsepushplugin.ParsePushPlugin$1.run(ParsePushPlugin.java:83)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)```

**Comment by taivo** [comment]
Hmm, I'm not able to replicate this with the included example app. However, the NullPointerException having to do with ParseInstallation is likely due to Parse not having been initialized. Does your app happen to use its own MainApplication class instead of this plugin's ParsePushApplication? 

If so, please see the `Advanced Configuration` section of the README for explanation on this.

If not, the plugin installation hook may not have worked correctly (to set ParsePushApplication as the main application). Can you remove then add the plugin and let me know of any error message that may have occurred?

Finally, there is no need to call ParsePushPlugin.initialize() on Android. At the time you created this issue, `initialize` was an undocumented experimental feature that's meant for iOS. It's since been changed to `register` and is still meant only for iOS.

**Comment by taivo** [comment]
Also, if possible, please post the content of your `platforms/android/AndroidManifest.xml` with private data redacted. Or at the very least, post the full `<application>` tag with all its attributes from that file (after having reinstalled the plugin. It would help me fix this problem for you.

**Comment by taivo** [comment]
Hi @Br3nda , so were you able to work through this issue? If so, please share with me what the problem was so I can update the docs or revise the code to help others in the future. Thanks!

FYI: in other issues where strange things happened that are related to Parse init, other people have reportedly use the Parse Javascript key instead of the client key in `config.xml`. Just in case that may be relevant, please make sure you use the client key.

If you still have problems, give me some info/feedback and I'd be glad to offer help.

**Comment by taivo** [comment]
Closing due to lack of response from requester. Most likely just a setup issue.

**Comment by Br3nda** [comment]
sorry for lack of response - this hit my spam folder for some reason.

I was calling initialise() in desperation to stop the crashes. 

We don't have our own MainApplication.

Posting our AndroidManifest in case anyone else hits this problem and this info may be useful.

```
<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="10001" android:versionName="1.0.1" package="nz.co.fish4all.app" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@drawable/icon" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:screenOrientation="portrait" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/fb_app_id" />
        <meta-data android:name="com.facebook.sdk.ApplicationName" android:value="@string/fb_app_name" />
        <activity android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:label="@string/fb_app_name" android:name="com.facebook.FacebookActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" />
        <service android:name="com.parse.PushService" />
        <receiver android:exported="false" android:name="github.taivo.parsepushplugin.ParsePushPluginReceiver">
            <intent-filter>
                <action android:name="com.parse.push.intent.RECEIVE" />
                <action android:name="com.parse.push.intent.DELETE" />
                <action android:name="com.parse.push.intent.OPEN" />
            </intent-filter>
        </receiver>
        <receiver android:name="com.parse.GcmBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="nz.co.fish4all.app" />
            </intent-filter>
        </receiver>
    </application>
    <uses-sdk android:minSdkVersion="15" android:targetSdkVersion="23" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <permission android:name="nz.co.fish4all.app.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="nz.co.fish4all.app.permission.C2D_MESSAGE" />
</manifest>
```

**Comment by taivo** [comment]
@Br3nda 
It looks like the `<application>` tag in your manifest is missing the attribute that would point to the correct initialization code, so the Parse crash makes sense. 

The missing attribute is `android:name="github.taivo.parsepushplugin.ParsePushApplication"` This is supposed to be added via the `before_install` hook so something must have gone wrong during plugin installation. You can either remove and re-add the latest version of this plugin or manually add `android:name="github.taivo.parsepushplugin.ParsePushApplication"` to your `<application>` tag.

If you choose the first option and error messages show up, please let me know of them.

Thanks
