### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by andrewfam** [taivo/parse-push-plugin#6]
![screen shot 2015-09-18 at 10 10 47 pm](https://cloud.githubusercontent.com/assets/1430616/9961274/3135d658-5e52-11e5-8c7c-c733ef2d30c3.png)

**Comment by filfat** [comment]
+1

**Comment by renatomolina** [comment]
+1 any idea?

**Comment by tavojavi** [comment]
Hi Andrew, did you follow the instructions on section for android ? "Phonegap/Cordova doesn't define a custom android.app.Application",..

I think it might be related not declaring a MainApplication object that extends Application, and just using the mainActivity extends CordovaActivity in your project.

regards

**Comment by taivo** [comment]
Sorry for the slow response. I've been swamped with my main projects (the projects for which I needed this fork of parse-push-plugin). It's been a while I haven't encountered this error. @tavojavi 's answer is on point.

Please review the https://github.com/taivo/parse-push-plugin#android-setup section of the docs and let me know if that doesn't work for you.

Also, to everyone following this issue, I'm open to ideas for restructuring the docs to make it easier to follow.

Thanks!

**Comment by brunojabs** [comment]
@taivo I think that the instructions are pretty clear. Worked for me.

I have one suggestion: on my project, I wrote a hook that creates custom ```Application``` file and add the property ```android:name:"CustomActivity"``` to the ```AndroidManifest.xml```. 

Maybe we don't have to make this hook default, because some projects can have its own application files, but the users can add the hook as an alternative to make things easier.

What do you think about add this script to the project?

**Comment by taivo** [comment]
Ah sounds interesting. I personally like the idea of dealing with Java as little as possible when working on a Phonegap project. Having such a hook would be especially useful for newcomers of Phonegap and Parse.

That said, I'm a bit swamped right now to get that going, plus I think my next priority should be to get iOS support. If the hook you wrote is general enough for others to use, can you put in a PR?

**Comment by brunojabs** [comment]
Sure, I'll submit a PR soon. :smile:

BTW probably I'll need the iOS support soon, so I'm willing to help you in this part, considering that I would implement it anyway

Tks!
