### ISSUE TITLE
Invalid plugin.xml

### ISSUE THREAD

**Issue by antonino-tocco** [taivo/parse-push-plugin#60]
Hi, I tried to install the plugin via Visual Studio for Windows App but the plugin.xml is invalid for this IDE.

**Comment by taivo** [comment]
Hello,
It should install if you use the standard `cordova plugin add https://github.com/taivo/parse-push-plugin` as mentioned in the docs.

That said, UWP support is currently a work in progress. It's not working yet so I did not mention it in the docs. I'm completely new to UWP programming so I'm inching very slowly towards making it work. If you are experienced in Cordova UWP, we can really use your pull requests.

Related to issue #42

**Comment by Missile71** [comment]
by changing this row
`<plugin xmlns="http://www.apache.org/cordova/ns/plugins/1.0" id="parse-push-plugin" version="1.0.4">`
to this
`<plugin xmlns="http://www.apache.org/cordova/ns/plugins/1.0" xmlns:android="http://schemas.android.com/apk/res/android" id="parse-push-plugin" version="1.0.4">`
and this
`<receiver android:exported="false" android:name="github.taivo.parsepushplugin.ParsePushPluginReceiver" android:exported="false">`
to this
`<receiver android:exported="false" android:name="github.taivo.parsepushplugin.ParsePushPluginReceiver">`
the plugin.xml will work for visual studio too

**Comment by taivo** [comment]
Closing. Fixed by 209081f67da3883d678216275b0a9ceaa3931684
