### ISSUE TITLE
Tracking Pushes and App Opens

### ISSUE THREAD

**Issue by pablo-gonzalez** [taivo/parse-push-plugin#64]
Hi Taivo

Parse Dashboard is displaying Open Pushs = 0 for all PN for Android.
However it is working for iOS.

According to Parse docs:
http://parseplatform.github.io/docs/android/guide/#tracking-pushes-and-app-opens
 

> The default implementation of onPushOpen will automatically track user engagment from pushes. If you choose not to use the ParsePushBroadcastReceiver or override the onPushOpen implementation, you may need to track your app open event manually. To do this, add the following to the onCreate method of the Activity or the onReceive method of the BroadcastReceiver which handles the com.parse.push.intent.OPEN Intent:
> 
> ParseAnalytics.trackAppOpened(getIntent());
> 
> To track push opens, you should always pass the Intent to trackAppOpened. Passing null to trackAppOpened will track only a standard app-opened event, not the push-opened event. 
> 
> 

I have realized that you added that in ParsePushPluginReceiver.java
`ParseAnalytics.trackAppOpened(intent);`

I am not a Java programmer so I am not sure why the tracking is not working as expected.
Is this a Parse or plugin issue? Is this working for you?

Thanks in advance,
Pablo

**Comment by pablo-gonzalez** [comment]
Update: I guess it was a Parse issue. Today's PN are tracking for both iOS and Android.

**Comment by NBAMj** [comment]
I installed Parse server localay and everything is working as expected except for tracking "Opened" Pushes.
I can see number of push notifications sent but not how many opened.
Do I have to call anything from Javascript side to call or enable `ParseAnalytics#trackAppOpened(intent)` ?

**Comment by kronicali** [comment]
@NBAMj same issue, did you solve?

**Comment by NBAMj** [comment]
Nope the issue still exists
