### ISSUE TITLE
Receiving Push but not triggering default notification

### ISSUE THREAD

**Issue by vkeepe** [taivo/parse-push-plugin#68]
I am receiving push notification as I can see in the logs when I have explicitly defined receivePN. I was expecting it to show default pushing notification icon, default sound and dialog box. Am I wrong in my assumption?

I am using parse-server and I am on Android 5.x

**Comment by taivo** [comment]
Dialog box is not automatic. You have to display that on your own in your custom receivePN handler. This way you can style the dialog or process the pn in a more subtle way
