### ISSUE TITLE
Auto Registration on iOS

### ISSUE THREAD

**Issue by stevecarlton** [taivo/parse-push-plugin#69]
I am at my wits end as to why I keep getting the iOS registration prompt at startup even when I have 
`<preference name="ParseAutoRegistration" value="false"/>` set in config.xml

I have tested through simulator, Xcode -> Device and TestFlight with the same result. Any ideas why this might be happening or how I could resolve this?

**Comment by taivo** [comment]
Hi,

Does your javascript code unintentionally call `register` on start up?

If not, I'll have to look at this later this week as I'm unable to do so right now. You can also tinker with the `.m` files yourself if you'd like. Just grep for `registerForPN`. That method actually carries out the registration and thus trigger the iOS prompt. 

A good place to start would be `AppDelegate+parsepush.m: didFinishLaunchingWithOptions` as that method decides whether to call `registerForPN` on app start up.

Please keep me posted if you see other symptoms that may be useful for debugging. I'll help you more later this week when I get a chance.

**Comment by taivo** [comment]
Any feedback on this, @stevecarlton ?

**Comment by dowsanjack** [comment]
@taivo I am using v1.0.5, at first I thought that the version is a problem, I was using v0.9

But, still I'm getting the prompt for notification, even before the `app.ready` fires. Also, in `AppDelegate+parsepush.m: didFinishLaunchingWithOptions` the call for `registerForPN` looks like this:

      if(!autoReg.length || [autoReg caseInsensitiveCompare:@"true"] || [application isRegisteredForRemoteNotifications]){
          // if autoReg is true or nonexistent (defaults to true)
          // or app already registered for PN, do/redo registration
          //
          // Note: redo registration because APNS device token can change and Apple
          // suggests re-registering on each app start. registerForPN() is idempotent so
          // no worries if it gets called multiple times.
          [pluginInstance registerForPN];
      }


Any idea, where I might have gone wrong.

**Comment by taivo** [comment]
@dowsanjack , have you set `<preference name="ParseAutoRegistration" value="false"/>` in config.xml?

**Comment by dowsanjack** [comment]
@taivo yes, the config.xml has that one from the starting.

**Comment by stevecarlton** [comment]
@taivo @dowsanjack I did some additional debugging and this seems to be an issue in the plugin with auto registration. 

I added some native console logging and verified that the following are properly captured in the native code:
```
NSString *appId      = [pluginInstance getConfigForKey:@"ParseAppId"];
NSString *serverUrl  = [pluginInstance getConfigForKey:@"ParseServerUrl"];
NSString *clientKey  = [pluginInstance getConfigForKey:@"ParseClientKey"];
NSString *autoReg    = [pluginInstance getConfigForKey:@"ParseAutoRegistration"];
```
Console Log: `ParsePush: autoReg: false`

This results in Auto Registration Firing:
```
if(!autoReg.length || [autoReg caseInsensitiveCompare:@"true"] || [application isRegisteredForRemoteNotifications]){
          // if autoReg is true or nonexistent (defaults to true)
          // or app already registered for PN, do/redo registration
          //
          // Note: redo registration because APNS device token can change and Apple
          // suggests re-registering on each app start. registerForPN() is idempotent so
          // no worries if it gets called multiple times.
         [pluginInstance registerForPN];
         NSLog(@"ParsePush: Auto Registration Fired");
      }
```

Removing the `caseInsensitiveCompare` from the if statement (testing for both true and false) keeps auto registration from firing:
```
if(!autoReg.length || [application isRegisteredForRemoteNotifications]){
          // if autoReg is true or nonexistent (defaults to true)
          // or app already registered for PN, do/redo registration
          //
          // Note: redo registration because APNS device token can change and Apple
          // suggests re-registering on each app start. registerForPN() is idempotent so
          // no worries if it gets called multiple times.
         [pluginInstance registerForPN];
         NSLog(@"ParsePush: Auto Registration Fired");
      }
```

Any ideas?
