### ISSUE TITLE
Breaks Windows build

### ISSUE THREAD

**Issue by filfat** [taivo/parse-push-plugin#7]
When using the plugin the windows build of the applications crashes with "Parse is undefined". Maybe doing some undefined checking would be a quick solution? ;)

**Comment by taivo** [comment]
I checked in a new version 1 day before you logged this issue. This version no longer requires Parse js. You can either update or put parse.js before your cordova.js in index.html.

If this is another type of crash, post the relevant logcat messages here and I'll see what I can do on my end. Thanks for using and giving feedback!
