### ISSUE TITLE
Cold Start On click Of System Tray Notification

### ISSUE THREAD

**Issue by mohsinAjency** [taivo/parse-push-plugin#73]
On Click Of Notification from system tray openPN doesnt get triggered. Any solution to this  ??

**Comment by quilligana** [comment]
What platform are you on @mohsinAjency? Are you talking coldstart, in background, foreground? We've done some digging on this previously in #24.

**Comment by mohsinAjency** [comment]
yeah its the same issue. I am currently working on Android.

**Comment by quilligana** [comment]
#24 has been resolved @mohsinAjency. You need to give us more details on your particular situation. Please test if it is the same result for when the notification launches a coldstart and when the app is running in the background. 

Also, what version of the plugin are you running? Try removing the plugin from your project and reinstalling from git, `cordova plugin add https://github.com/taivo/parse-push-plugin`.

**Comment by rooswelt** [comment]
Same issue for me only on Android (iOS works fine)
Only on coldstart
Using last plugin version
OP3 running stock Android 6.0.1

**Comment by rooswelt** [comment]
In parse-push-plugin.js moving ParsePushPlugin declaration **before** calling `registerCallback` seems to resolve the problem.

Unfortunately cannot PR my repo 'cause I also edited other things specific for my project.

Hope it helps

**Comment by taivo** [comment]
I increased `_coldStartDelay` ask @rooswelt. It's really a temp hack, a real solution should be event based and not based on fixed wait time ... but in a time constrained world, I guess it's good enough for now. Please reopen issue if it recurs. Thanks.

**Comment by ericgopak** [comment]
Thank you all for the feedback!
I'll try to implement a proper event-based solution for this issue in [my fork](https://github.com/ericgopak/parse-push-plugin) of your repo :+1:
