### ISSUE TITLE
Provisioning Profile for iOS

### ISSUE THREAD

**Issue by jimcamut** [taivo/parse-push-plugin#76]
When I submit my app to the iOS app store, they send me an email/warning: 

"Missing Push Notification Entitlement - Your app includes an API for Apple's Push Notification service, but the aps-environment entitlement is missing from the app's signature."

Is it critical to address for push to work? Or can this be ignored?

**Comment by taivo** [comment]
You'll need to look up how to add push notification entitlement to your app. If I remember correctly, this can be done with just a few clicks in either XCode or in your apple developer dashboard. 

I've always added this entitlement pre-emptively and never experimented with push without it.

**Comment by jimcamut** [comment]
Thanks for the reply. It turns out I was submitting with the incorrect provisioning profile - should have been more obvious. When I submitted with a new one that had push notifications enabled, everything turned out peachy.
