### ISSUE TITLE
Installation not created for Android

### ISSUE THREAD

**Issue by yingliangzhang** [taivo/parse-push-plugin#79]
Hi,

This seems like a known issue and it's happening to me as well. I tried to remove the `platforms` and `plugins` folder and run `ionic state restore` but no luck. It was working previously and not sure since when it stopped creating installations for my Android device.

All I did was install the plugin, add `config.xml` values and call

```
ParsePushPlugin.subscribe('Default', (msg) => {
      return;
  }, function(error) {
      throw error;
  });
```

Any idea?
Thanks!

**Comment by yingliangzhang** [comment]
OK I just rebooted the device and it fixed itself! Not sure why but seems like completely uninstall and reinstall the app doesn't help solving this.

**Comment by rooswelt** [comment]
I have the same problem, but still does not work even after reboot

**Comment by taivo** [comment]
If by chance you have removed and re-add the Android platform, please also do the same for the plugin. 

There is a post-installation step for the plugin that modifies the android manifest and point your application to the appropriate push notification handler. Resetting the Android platform also resets your manifest back to default, so reinstalling the plugin makes things right again.

**Comment by max-at-brili** [comment]
I am also having this issue. For me it seems related to the post-installation step you mentioned but sometimes it is also fixed by a reboot. In particular my parse server responds to push registration without error, returning a response with an objectId and createdAt property. But when I query the objectID or try to update the installation with channel information I get the response "error: ParseError { code: 101, message: 'Object not found for update.' }"

**Comment by temitope** [comment]
I was able to find some relief by adding missing the trailing slash "/" on my parserServerURL variable on the config.xml file. Some more details on my entry in #70

**Comment by yingliangzhang** [comment]
Holy shit, thank you very much @temitope. This got me again today! I deployed my app to production and found out that no installation is created. Thank god I revisited the issue and found out missing the trailing slash "/" is the cause. I'm gonna add this into my project README.

**Comment by mihado** [comment]
In my case, I try to leverage Cloudflare & Heroku free SSL to enable https for free.

I think the Universal SSL free plan that Cloudflare offers is not compatiable with Parse Android SDK leading to a com.parse.ParseRequest$ParseRequestException: i/o failure, but it was not easy to arrive at this as the log is swallowed from Parse side.

I've sent PR https://github.com/taivo/parse-push-plugin/pull/85 to enable some logging to help with the debugging.

**Comment by taivo** [comment]
Thanks @mihado. Your logging PR is very helpful. Eventually, I should just automatically add a slash when there is none.
