### ISSUE TITLE
ANDROID - No error even if server is offline and getSubscriptions return cached value

### ISSUE THREAD

**Issue by rooswelt** [taivo/parse-push-plugin#80]
In Android (6.0) calling plugin method (subscribe, unsubscribe, etc.) when server is offline does not return any error

Moreover calling getSubscriptions return old invalid values (like they where cached) even if I kill and restart application

I think it is related to #79

**Comment by rooswelt** [comment]
Cleaning user data clears also cached values

**Comment by taivo** [comment]
This is more of a design decision of Parse SDK. All we do with the plugin is translating javascript calls into Parse SDK calls.
