### ISSUE TITLE
Migrating from benjie/phonegap-parse-plugin

### ISSUE THREAD

**Issue by max-at-brili** [taivo/parse-push-plugin#81]
I have a cordova application that runs on android and ios, using Parse.com currently for push notifications. I have setup a private Parse server and I am having trouble migrating my application to use your repository.

Could you list the process for switching an application such as mine to point to a private Parse server using your repo? I tried to follow the example but my application does not use cloud code, would I need to use the cloud code from the example in my Parse server? I apologize if these are beginner questions, for I am a bit of a beginner.

**Comment by taivo** [comment]
Hi @max-at-brili , this plugin took a very drastic turn away from the upstream fork over a year ago. Setup wise, it's probably better to think of this as an entirely different plugin.

For server and data migration (stuff outside of the scope of this plugin), please use guides provided by Parse.com or other independent tutorials. I wouldn't be able to give you the same level of clarity as those can when it comes to server migration. 

That said, in the Installation section of this plugin's README, I also point to a mini tutorial that I have for setting up an extremely barebone local parse-server that would for sure work with this plugin. Going through it once may give you a template to start making changes from. https://taivo.github.io/guides/parse-server-for-local-development

If you are already passed these points, please review the Installation section of the README. You don't need Cloudcode for push notification or this plugin to do it's job (receive push notification). But you will need Cloudcode eventually on your server to send notifications. The main issue now is pointing to your open source parse server with `config.xml` parameters. The example app and server that I included in this repo only uses cloudcode to initiate push notification and get some return status back to the example app.

Hope that helps a bit. To be of further help, I will need more specifics, e.g., code, config.xml, etc.

**Comment by max-at-brili** [comment]
Thank you for the clarification @taivo
