### ISSUE TITLE
Parse server says push is sent, but no push shows up

### ISSUE THREAD

**Issue by urbanmania** [taivo/parse-push-plugin#84]
Hi

I'm using Back4App as the parse server.  Things have been working fine, but now working on an update to the app and then pushes stopped working.  The server says the push is sent and I can see the installation being created, but the device don't show any sign of the push.  Any pointers on what I have messed up?

Johannes

**Comment by max-at-brili** [comment]
This recently caused me trouble, if you were sending pushes to android you may be affected as well:

https://github.com/parse-server-modules/parse-server-push-adapter/issues/35

**Comment by urbanmania** [comment]
Thanks for the suggestion, but as it's both affecting iOS and Android I'm guessing it's something on my side.

**Comment by urbanmania** [comment]
Now Android is working for me (after deleting the firebase project and setting it up again) but iOS is still out. Any idea?

**Comment by urbanmania** [comment]
I've re-generated the certs for Apple, but the server logs give me 
 - parse-server-push-adapter APNS cannot find vaild connection

**Comment by urbanmania** [comment]
After re-creating all certificates and re-building everything, the pushes seem to be working again.  Must have been caused by me ill-fated play with Firebase Cordova plugin :)
