### ISSUE TITLE
[iOS] Notification received but 'openPN' event not triggered.

### ISSUE THREAD

**Issue by ericgopak** [taivo/parse-push-plugin#91]
Hey, and thanks a lot for the plugin.

I am using the plugin both for Android and iOS. It works fine on Android, but doesn't seem to work on iOS.

Some warnings/errors that I can see being printed out are below (not sure if relevant):
```
nw_socket_get_input_frames recvmsg(fd 10, 1024 bytes): [57] Socket is not connected
nw_socket_get_input_frames recvmsg(fd 11, 1024 bytes): [57] Socket is not connected
nw_socket_get_input_frames recvmsg(fd 17, 1024 bytes): [57] Socket is not connected
nw_socket_get_input_frames recvmsg(fd 25, 1024 bytes): [57] Socket is not connected
nw_socket_get_input_frames recvmsg(fd 26, 1024 bytes): [57] Socket is not connected
...
nw_endpoint_handler_add_write_request [1.1 172.217.16.170:443 failed socket-flow (satisfied)] cannot accept write requests
__tcp_connection_write_eof_block_invoke Write close callback received error: [22] Invalid argument
(several more of these...)
...
```
Right after these messages I can see that the plugin has received the push notification, because it prints out:
```
User info {
aps = ...
...
}
```

However, the callback function for `openPN` event does not get triggered. I use it like this (just like in the Readme):
```
ParsePushPlugin.on('openPN', function (pn) {
	console.warn('YO!!!');
}
```

Extra details:

- this happens only on iOS10 (iPad 2 mini), but works nicely on Android.
- the callback function seems to be triggered if I install the app from AppStore and not FlightApp or local machine (not 100% sure about it though, I could be wrong here).

**Comment by kudeiro** [comment]
same problem here

**Comment by ericgopak** [comment]
Reverting back to commit `69fba55fefd4eccfed3f92c956c700b8b731942b` resolved the issue for me.

Until this is fixed one can remove the plugin with `cordova rm parse-push-plugin`
and install that specific revision:
`cordova add https://github.com/taivo/parse-push-plugin#69fba55fefd4eccfed3f92c956c700b8b731942b`

Thanks again for the plugin!

**Comment by avilasolucoes-naora** [comment]
see #94

**Comment by taivo** [comment]
closing this because it seems @avilasolucoes-naora's contribution addressed this.
